### ISSUE TITLE
.npmignore ignored by dual-publish

### ISSUE THREAD

**Issue by L2jLiga** [ai/dual-publish#1]
For example I have `example` folder ignored by `.npmignore`
When I run `dual-publish` then this directory also copied, processed and added to "exports" in `package.json`

**Comment by ai** [comment]
Do you have idea how we can improve our current ignoring code?

https://github.com/ai/dual-publish/blob/master/process-dir.js#L154

**Comment by L2jLiga** [comment]
I will take a look when I will have time

**Comment by alik0211** [comment]
@ai can I fix this?

**Comment by ai** [comment]
@alik0211 sure
