### ISSUE TITLE
Enhance exports field

### ISSUE THREAD

**Issue by vankop** [ai/dual-publish#12]
Would be great to support additional exports field conditions regarding to [webpack guideline](https://gist.github.com/sokra/e032a0f17c1721c71cfced6f14516c62#reference-syntax)

`<root>.style` => `<root>.exports.style`
`<root>.sass` => `<root>.exports.sass`
`<root>.types` => `<root>.exports.types`
`<root>.exports.import` => `<root>.exports.module` not sure that this is possible. This condition requires only esm subtree (esm->...->cjs disallowed).

**Comment by ai** [comment]
Sure. Can you send a PR?

**Comment by evilebottnawi** [comment]
<root>.less => <root>.exports.less
<root>.styl => <root>.exports.styl

**Comment by vankop** [comment]
> `<root>.less` => `<root>.exports.less`
> `<root>.styl` => `<root>.exports.styl`

added

**Comment by ai** [comment]
Released at 0.11
