### ISSUE TITLE
Support "development" and "production" conditions

### ISSUE THREAD

**Issue by guybedford** [ai/dual-publish#14]
Just like `.browser` is automatically detected it would be nice to automatically detect `.browser.development` to mean the `"browser": { "development" }` exports entry.

If there were eg both a `index.browser.js` and `index.browser.development.js` then it would infer `"browser": { "development", "default" }`.

This would then enable https://github.com/ai/nanoid/issues/237#issuecomment-703135919.

**Comment by ai** [comment]
Let’s do `index.dev.js` and `index.browser.dev.js`

**Comment by guybedford** [comment]
It could even be nice to dynamically split on the `.` characters and have a well defined grammar mapping in general to allow full flexibility.

**Comment by ai** [comment]
Completely have no time for this issue.

Will be glad for PR.

**Comment by ai** [comment]
Fixed in https://github.com/ai/dual-publish/pull/16 by @AleksandrSl
