### ISSUE TITLE
Usage with `np`

### ISSUE THREAD

**Issue by yumauri** [ai/dual-publish#3]
I want to use this tool alongside with `np`, is it possible?
https://github.com/sindresorhus/np

As I see it, `np` supports argument `--contents` to specify folder to publish. For now I have script
```
"release": "np --yolo --no-release-draft",
```
so with `dual-publish` it should be smth like this
```
"release": "dual-publish --check && np --yolo --no-release-draft --contents ./dual-publish-tmp",
```
?

**Comment by yumauri** [comment]
Update:
Nope, calling `dual-publish` before `np` is not possible, because `np` changes version in main package.json...

**Comment by ai** [comment]
Sorry, I never used `np` before. I can’t help here.

If you will find a way, please send PR.
