### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by yumauri** [ai/dual-publish#4]
I understand this tool is aimed for JS, without build step, but I want to write in TypeScript.

And there is one issue — TypeScript generates CommonJS modules like

```
Object.defineProperty(exports, "__esModule", { value: true });
exports.x = function () {
```
and when I try to use dual-publish on TS output files, I get:
```
 ERROR  Replace module.exports.x to module.exports = { x } at index.js:2:63
```

**Comment by ai** [comment]
@yumauri by using `dual-publish` with TypeScript you will lose att “no build step” features. You users still will not be able to use your project from GitHub.

Also, you do not need a “readable sources” feature.

I think it is better to create another build chain on top fo the TypeScript compiler.

**Comment by yumauri** [comment]
Ok, fair enough ¯\\\_(ツ)\_/¯
