### ISSUE TITLE
Add the ability to select folders for publishing

### ISSUE THREAD

**Issue by alik0211** [ai/dual-publish#5]
I tried adding dual-publish to [@mtproto/core](https://github.com/alik0211/mtproto-core).

I get the following error when I run `npx dual-publish --check`, because dual-publish iterates through all JS files:
![image](https://user-images.githubusercontent.com/16985862/78797265-83cea700-79c8-11ea-802c-42b56847ded4.png)

Maybe we should add support for the fields of the `files` package.json? Or any other way to filter files?

**Comment by ai** [comment]
Do you use blacklist in `.npmignore` or whitelist in `package#files`?

**Comment by alik0211** [comment]
I use `package#files` - https://github.com/alik0211/mtproto-core/blob/master/package.json#L26-L29

**Comment by ai** [comment]
Can I ask you to help me here?

You need to insert code here https://github.com/ai/dual-publish/blob/master/process-dir.js#L169-L178

I will write a test

**Comment by alik0211** [comment]
Yes, I will do PR in the next few days
